baseURL = "https://me.taufiqhdyt.com/"
languageCode = "en-us"
title = "TaufiqHdyt"
enableRobotsTXT = true

[params]
  author = "TaufiqHdyt"
  description = "About TaufiqHdyt and His Works"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = true
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = true
    simple = true
  [privacy.youtube]
    disable = true
    privacyEnhanced = true