backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'gallery'
    label: 'Gallery'
    folder: 'content/gallery'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'portofolio'
    label: 'Portofolio'
    folder: 'content/portofolio'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'quote'
    label: 'Quote'
    folder: 'content/quote'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Quote by', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }